server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/todo
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop
